import type { Word } from "./words";

export const emojis = {
  // ABBÉ: "",
  ACNE: "🧴",
  ADEL: "👑",
  ADJÖ: "👋",
  // ADLA: "",
  ADSL: "🌐",
  AGAD: "😱",
  // AGAN: "",
  // AGAR: "",
  // AGAS: "",
  AGAT: "💎",
  // AGGS: "",
  // AGIL: "",
  // AGNS: "",
  AIDS: "🎗️",
  AIRS: "💨",
  AKNE: "🧴",
  AKTA: "⚠️",
  // AKTS: "",
  AKUT: "🚑",
  ALAR: "🌳",
  ALEN: "🌳",
  // ALFS: "",
  // ALGS: "",
  ALKA: "🐦",
  ALLA: "👥",
  // ALLE: "",
  ALLÉ: "🌳",
  // ALLO: "",
  // ALLS: "",
  // ALLT: "",
  ALMS: "🌳",
  ALPS: "🏔️",
  ALVS: "🧝",
  AMEN: "🙏",
  AMMA: "🤱",
  AMOK: "🤪",
  // ANAD: "",
  ANAL: "🍑",
  // ANAR: "",
  // ANAS: "",
  // ANAT: "",
  ANDA: "💨",
  ANDE: "👻",
  // ANDS: "",
  // ANGÅ: "",
  ANGE: "📝",
  ANKA: "🦆",
  // ANNO: "",
  ANOD: "🔋",
  // ANOR: "",
  ANSA: "✂️",
  // ANSE: "",
  // ANTA: "",
  // ANTE: "",
  ANTI: "🚫",
  ANUS: "🍑",
  APAN: "🐵",
  // APAR: "",
  // APAS: "",
  // APAT: "",
  APEL: "🍎",
  APOR: "🐒",
  APPS: "📱",
  // AQAP: "",
  // AQIM: "",
  // ARAB: "",
  AREA: "📐",
  ARGA: "😡",
  ARGE: "😡",
  ARGT: "😡",
  ARIA: "🎶",
  ARKS: "📄",
  ARMA: "😢",
  // ARME: "",
  ARMÉ: "🪖",
  ARMS: "💪",
  // ARMT: "",
  AROM: "👃",
  // ARTA: "",
  ARTS: "🧬",
  // ARVS: "",
  // ASCH: "",
  // ASKA: "",
  // ASKS: "",
  ASPS: "🌳",
  ASYL: "🏠",
  ATOM: "⚛️",
  AUDI: "🚗",
  AULA: "🏫",
  AURA: "✨",
  AVEL: "🧬",
  AVEN: "🌳",
  AVES: "🐦",
  // AVET: "",
  // AVGÅ: "",
  // AVGE: "",
  // AVIG: "",
  // AVIN: "",
  // AVIS: "",
  // AVLA: "",
  AVOG: "😒",
  // AVSE: "",
  AVTA: "📉",
  AXEL: "💪",
  AXEN: "🌾",
  AXET: "🌾",
  AXLA: "🤷",
  AZER: "🇦🇿",
  AZUR: "🔵",
  BABY: "👶",
  BACK: "↩️",
  BÄCK: "💧",
  BÅDA: "👥",
  BADA: "🛁",
  BÄDD: "🛏️",
  BÅDE: "⚖️",
  // BADS: "",
  BÅGE: "🏹",
  // BAGS: "",
  BÅGS: "🏹",
  BAGS: "👜",
  BAJS: "💩",
  BAKA: "🍞",
  // BAKS: "",
  // BÅKS: "",
  BALK: "🏗️",
  BALL: "🏀",
  // BALS: "",
  BÅLS: "🔥",
  BANA: "🛣️",
  // BÄND: "",
  BAND: "🎸",
  // BÅNG: "",
  BANG: "😨",
  BANK: "🏦",
  BÄNK: "🪑",
  // BANN: "",
  // BÄNT: "",
  // BARA: "",
  BÄRA: "👐",
  BARA: "🦶",
  BARD: "🎭",
  BARK: "🌳",
  BARN: "🧒",
  BARR: "🌲",
  // BARS: "",
  // BÅRS: "",
  BÄRS: "🍺",
  BARS: "🍻",
  // BART: "",
  BASA: "👑",
  BÄST: "🏆",
  BÅTS: "🛥️",
  BÄVA: "😨",
  BAXA: "📦",
  BDSM: "⛓️",
  BEAT: "🥁",
  BEBO: "🏠",
  // BEDD: "",
  BEDS: "🛏️",
  // BEGÅ: "",
  // BEGE: "",
  BEHÅ: "👙",
  BENA: "💇",
  BENS: "🦵",
  BERG: "⛰️",
  // BERO: "",
  // BESÅ: "",
  // BESE: "",
  // BESK: "",
  BEST: "🐲",
  BETA: "🧪",
  BETE: "🌾",
  // BETS: "",
  BETT: "🦷",
  // BIDA: "",
  BIET: "🐝",
  BIFF: "🥩",
  BIKT: "⛪",
  BILA: "🪓",
  BILD: "🖼️",
  BILS: "🚗",
  BINA: "🐝",
  BIND: "🪢",
  BINS: "🐝",
  BION: "🎬",
  BIOS: "🎥",
  BIRA: "🍺",
  BITA: "🦷",
  BITR: "🧑‍💼",
  BITS: "💾",
  // BJÖD: "",
  BJUD: "🎁",
  BLÅA: "🔵",
  BLAD: "🍃",
  BLÅE: "🔵",
  BLÄS: "🐴",
  BLÅS: "💨",
  BLEK: "😶",
  // BLEV: "",
  // BLID: "",
  // BLIR: "",
  // BLIV: "",
  BLOD: "🩸",
  BLÖD: "🩸",
  BLÖT: "💧",
  BLUS: "👚",
  BLYG: "😳",
  BLYS: "✏️",
  // BOAN: "",
  BOAS: "🐍",
  BOCK: "🐐",
  BODS: "🛖",
  BOET: "🪺",
  // BOGS: "",
  BÖGS: "🏳️‍🌈",
  // BOJA: "",
  BÖJA: "↩️",
  BOJA: "⛓️",
  // BÖJD: "",
  // BÖJS: "",
  // BÖJT: "",
  BÖKA: "🐗",
  BOKA: "📖",
  BOKS: "📖",
  BOLA: "⚽",
  BÖLA: "😭",
  BÖLD: "🩹",
  BOLL: "⚽",
  BOMB: "💣",
  BOMS: "💥",
  // BONA: "",
  BÖNA: "🌱",
  BÖNE: "🙏",
  BONG: "🌿",
  // BONS: "",
  BÖNS: "🫘",
  BOOM: "💥",
  // BOOR: "",
  // BÖRA: "",
  // BÖRD: "",
  BORD: "🍽️",
  BORG: "🏰",
  BORR: "🛠️",
  // BORS: "",
  BÖRS: "💰",
  // BORT: "",
  BOSS: "🧑‍💼",
  BOTA: "💊",
  BÖTA: "💸",
  // BOTS: "",
  // BÖTS: "",
  BOTS: "🤖",
  // BOTT: "",
  BOVS: "🦹",
  BOXA: "🥊",
  // BRÅD: "",
  BRÄD: "🪵",
  // BRÄK: "",
  BRÅK: "⚔️",
  BRAK: "💥",
  // BRÄM: "",
  // BRÅS: "",
  BRED: "↔️",
  // BRER: "",
  // BRES: "",
  BREV: "✉️",
  BRÖA: "🍞",
  BRÖD: "🍞",
  BROM: "🧪",
  BRON: "🌉",
  BROR: "👦",
  BROS: "👬",
  // BRÖT: "",
  BRUD: "👰",
  BRUK: "🏭",
  BRUN: "🟫",
  BRUS: "📻",
  BRYN: "🤨",
  // BRYR: "",
  BRYT: "💔",
  // BUAR: "",
  // BUAS: "",
  // BUAT: "",
  BUDA: "💰",
  // BUDS: "",
  BUGA: "🙇",
  BUGG: "🐞",
  // BUKS: "",
  BUKT: "🌊",
  BULA: "🤕",
  BULT: "🔩",
  // BUMS: "",
  BUNT: "💐",
  BURA: "🐦",
  BURK: "🥫",
  // BURS: "",
  BUSA: "🤪",
  BUSE: "😈",
  BUSH: "🌳",
  BUSK: "🌿",
  BUSS: "🚌",
  BYAR: "🏘️",
  // BYBO: "",
  BYGD: "🏞️",
  BYGG: "🏗️",
  BYIG: "💨",
  // BYKS: "",
  // BYNS: "",
  // BYOD: "",
  BYRÅ: "🗄️",
  BYST: "👤",
  BYTA: "🔄",
  BYTE: "🔄",
  // BYTS: "",
  // BYTT: "",
  BYXA: "👖",
  CAFÉ: "☕",
  CASH: "💰",
  CELL: "🔬",
  CENT: "🪙",
  CHEF: "🧑‍💼",
  CHIC: "💅",
  CHIP: "💾",
  CIGG: "🚬",
  CISS: "🎵",
  CITY: "🌆",
  COLT: "🐎",
  COOL: "😎",
  CRED: "👍",
  // CSKA: "",
  CUPS: "🏆",
  CUTT: "✂️",
  DÄCK: "🛞",
  DÅDS: "☠️",
  DAGA: "🌅",
  DAGG: "💧",
  DAGS: "⏰",
  DALA: "📉",
  // DALS: "",
  // DALT: "",
  DAMM: "🧹",
  // DAMP: "",
  DAMS: "👩",
  DANA: "🛠️",
  DÅNA: "💥",
  DÄNG: "👊",
  // DÅNS: "",
  DANS: "💃",
  DÅRA: "🤡",
  DÅRE: "🤡",
  // DÄRI: "",
  DARR: "😬",
  // DARS: "",
  DART: "🎯",
  DÅSA: "😴",
  DASK: "🖐️",
  DASS: "🚽",
  // DÄST: "",
  DATA: "💻",
  DATE: "❤️",
  // DATT: "",
  DDR3: "💾",
  DEAL: "🤝",
  // DEGS: "",
  DEJT: "❤️",
  DELA: "🔗",
  // DELO: "",
  // DELS: "",
  DEMO: "📢",
  // DENS: "",
  DEPÅ: "🏭",
  // DESS: "",
  // DIAD: "",
  DIAR: "🤱",
  // DIAS: "",
  // DIAT: "",
  DIET: "🥗",
  DIKA: "🚧",
  DIKE: "🕳️",
  DIKT: "📝",
  DILL: "🌿",
  // DIMP: "",
  DINA: "👉",
  DING: "🤪",
  // DINS: "",
  DIOD: "💡",
  DIPP: "🥣",
  DIPS: "🥣",
  DIRK: "🗡️",
  DISK: "🍽️",
  DISS: "👎",
  // DITT: "",
  DIVA: "🎤",
  DJUP: "🌊",
  DJUR: "🐾",
  // DOAN: "",
  // DOAR: "",
  // DOAS: "",
  // DOAT: "",
  // DOBB: "",
  // DOCK: "",
  DÖDA: "☠️",
  DÖDE: "☠️",
  DÖDS: "☠️",
  DOFT: "👃",
  DOGM: "📜",
  DOJA: "👟",
  // DÖKS: "",
  DOLD: "🙈",
  DÖLJ: "🙈",
  DOLK: "🗡️",
  DOLT: "🙈",
  DÖMA: "🧑‍⚖️",
  DÖMD: "🧑‍⚖️",
  // DOMS: "",
  DÖMS: "🧑‍⚖️",
  DÖMT: "🧑‍⚖️",
  // DÖNA: "",
  // DONS: "",
  DOOR: "🚪",
  DÖPA: "✝️",
  DOPA: "💉",
  DOPP: "🏊",
  // DOPS: "",
  DÖPS: "✝️",
  DOPS: "💧",
  DÖPT: "✝️",
  DÖRR: "🚪",
  DOSA: "📦",
  DÖTT: "💀",
  // DOVA: "",
  DÖVA: "🧏",
  DOVA: "😴",
  // DOVE: "",
  // DÖVE: "",
  // DOVT: "",
  // DÖVT: "",
  DRAG: "🎭",
  DRÄM: "⚔️",
  DRÄP: "⚔️",
  DRÅP: "⚰️",
  DRAR: "🫳",
  // DRAS: "",
  DREV: "⚙️",
  DRIV: "🚗",
  DROG: "💊",
  DRÖJ: "⏳",
  DRÖM: "💭",
  DRÖN: "🔊",
  // DRÖP: "",
  // DRÖS: "",
  DRYG: "😒",
  DRYP: "💧",
  DUBB: "📌",
  // DUGA: "",
  DUGG: "🌧️",
  // DUGT: "",
  DUKA: "🍽️",
  DUKS: "🍽️",
  DUMT: "🤦",
  DUNK: "🛢️",
  DUNS: "💥",
  DUON: "👥",
  DUOR: "👥",
  DUOS: "👥",
  DURK: "🛳️",
  DURS: "🎼",
  DUST: "🥊",
  DUVA: "🕊️",
  // DYFT: "",
  DYGD: "😇",
  DYGN: "🕰️",
  DYKA: "🤿",
  DYKS: "🤿",
  DYKT: "🤿",
  DYNA: "🛋️",
  DYNS: "🛋️",
  DYRA: "💸",
  DYRE: "💸",
  DYRK: "🙏",
  DYRT: "💸",
  EBBA: "🌊",
  EDDA: "📖",
  EDEN: "🌳",
  // EDER: "",
  // EDET: "",
  // EDRA: "",
  // EFSA: "",
  // EGEN: "",
  // EGET: "",
  EGGA: "📣",
  EGGS: "📣",
  // EGNA: "",
  // EGNE: "",
  EGON: "👤",
  EGOS: "🪞",
  // EGOT: "",
  EHEC: "🦠",
  EKAN: "🛶",
  EKAR: "🌳",
  // EKAS: "",
  // EKAT: "",
  EKEN: "🌳",
  // EKER: "",
  EKON: "📢",
  EKOR: "🛶",
  // EKOS: "",
  EKOT: "🔊",
  ELAK: "😈",
  ELDA: "🔥",
  // ELDS: "",
  // ELEN: "",
  ELEV: "🧑‍🎓",
  ELIT: "🌟",
  ELVA: "1️⃣1️⃣",
  EMIR: "🕌",
  EMOT: "🆚",
  // ENAD: "",
  // ENAR: "",
  // ENAS: "",
  // ENAT: "",
  ENDA: "🔚",
  // ENDE: "",
  // ENEN: "",
  // ENES: "",
  ENIG: "🤝",
  // ENSE: "",
  EONS: "⏳",
  EPOK: "🕰️",
  EPOS: "📜",
  ERAN: "📆",
  // ERAS: "",
  // ERAT: "",
  EROR: "💘",
  ESSÄ: "📝",
  // ESTS: "",
  // ETER: "",
  ETIK: "⚖️",
  ETSA: "🧪",
  ETTA: "1️⃣",
  // ETTS: "",
  ETUI: "👝",
  // ETYD: "",
  EURO: "💶",
  EVIG: "♾️",
  // EXAD: "",
  // EXAR: "",
  // EXAS: "",
  // EXAT: "",
  // EXEN: "",
  // EXET: "",
  EXIL: "🧳",
  EXIT: "🚪",
  EXPO: "🖼️",
  FACK: "🗄️",
  // FADD: "",
  FAJT: "🥊",
  // FALA: "",
  FÄLG: "🛞",
  FALK: "🦅",
  // FALL: "",
  // FÅLL: "",
  // FÄLL: "",
  FALL: "🍂",
  FÅLL: "🧵",
  FÄLL: "🪤",
  // FALS: "",
  // FALT: "",
  FÄLT: "🌾",
  FAMN: "🤗",
  FANA: "🚩",
  // FANN: "",
  // FANS: "",
  FÅNS: "🤡",
  FARA: "⚠️",
  FÅRA: "🚜",
  // FARC: "",
  FÄRD: "🛣️",
  FÄRG: "🎨",
  FARM: "🚜",
  // FARS: "",
  // FÄRS: "",
  FÅRS: "🐑",
  FÄRS: "🥩",
  FART: "💨",
  FASA: "😱",
  // FAST: "",
  FÄST: "📌",
  FAST: "🔒",
  // FATS: "",
  // FATT: "",
  // FÅTT: "",
  FAUN: "🦌",
  FAXA: "📠",
  FEER: "🧚",
  FEGA: "🐔",
  // FEGE: "",
  // FEGT: "",
  // FEJA: "",
  // FEJD: "",
  FEJK: "🎭",
  // FEJS: "",
  FELA: "❌",
  // FELS: "",
  FEMS: "5️⃣",
  // FENA: "",
  // FENS: "",
  FEST: "🎉",
  FETA: "🧈",
  // FETE: "",
  // FETT: "",
  // FEZS: "",
  // FICK: "",
  FIKA: "☕",
  // FIKS: "",
  FILA: "🛠️",
  FILÉ: "🥩",
  FILM: "🎬",
  // FILS: "",
  FILT: "🛏️",
  FIMP: "🚬",
  // FINA: "",
  // FINE: "",
  FINK: "🐦",
  // FINN: "",
  // FINT: "",
  FIOL: "🎻",
  FIRA: "🎉",
  FISK: "🐟",
  FISS: "💨",
  FIXA: "🔧",
  // FIXT: "",
  FJÄR: "🦋",
  // FJOL: "",
  // FJOR: "",
  FJUN: "🪶",
  // FLAK: "",
  FLÄK: "💨",
  FLAK: "🚚",
  FLÅR: "🔪",
  // FLÅS: "",
  FLAT: "🏳️‍🌈",
  FLER: "➕",
  FLIK: "📑",
  FLIS: "🪵",
  // FLIT: "",
  FLOD: "🌊",
  // FLÖG: "",
  // FLÖT: "",
  FLOW: "🌊",
  FLUG: "🪰",
  FLUM: "🤪",
  FLYG: "✈️",
  // FLYR: "",
  // FLYS: "",
  FLYT: "🚣",
  // FNÖS: "",
  // FNYS: "",
  FOBI: "😱",
  FÖDA: "🍽️",
  FÖDD: "👶",
  // FÖDS: "",
  // FOGA: "",
  // FÖGA: "",
  FOGA: "🧩",
  // FOGS: "",
  FÖLA: "🐴",
  FÖLJ: "👣",
  FOLK: "🧑‍🤝‍🧑",
  // FÖLL: "",
  // FÖLS: "",
  FÖNA: "💇",
  FOND: "📈",
  // FORA: "",
  FÖRA: "🚗",
  // FÖRD: "",
  FÖRE: "⏮️",
  FORM: "🔷",
  // FORN: "",
  // FÖRR: "",
  // FORS: "",
  // FÖRS: "",
  // FORT: "",
  // FÖRT: "",
  FÖSA: "🫸",
  // FÖST: "",
  FOTA: "📸",
  FOTO: "📷",
  // FOTS: "",
  FÖTT: "👶",
  FOUL: "🟨",
  FRAM: "⏩",
  // FRÅN: "",
  // FRÄN: "",
  FRÅN: "↩️",
  FRÄN: "😎",
  // FRAS: "",
  FRÄS: "🔥",
  // FRÄT: "",
  FRED: "☮️",
  FRIA: "🆓",
  FRID: "🕊️",
  // FRIE: "",
  // FRIS: "",
  // FRÖA: "",
  // FROM: "",
  FRÖN: "🌱",
  // FRÖS: "",
  FRUN: "👩",
  // FRUS: "",
  // FRYN: "",
  FRYS: "❄️",
  FUKT: "💧",
  // FULA: "",
  // FULE: "",
  FULL: "🍺",
  // FULT: "",
  FUNK: "🎷",
  // FURA: "",
  // FURS: "",
  FUSK: "🃏",
  // FUXS: "",
  FYLL: "🍻",
  FYND: "💎",
  FYRA: "4️⃣",
  // FYRS: "",
  // GADD: "",
  GAGE: "💰",
  // GAGN: "",
  GALA: "🎭",
  GÄLD: "💸",
  // GÄLL: "",
  // GÄLS: "",
  GALT: "🐗",
  GAMA: "😮",
  GAME: "🕹️",
  // GAMS: "",
  // GÅNG: "",
  GÄNG: "👥",
  GÅNG: "🚶",
  GAPA: "😮",
  // GAPS: "",
  GÅRD: "🏡",
  GARN: "🧶",
  GARV: "😂",
  GASA: "⛽",
  // GASK: "",
  GÄSS: "🪿",
  // GAST: "",
  // GÄST: "",
  GAST: "👻",
  GÄST: "🧑‍🤝‍🧑",
  GÅTA: "❓",
  GATA: "🚦",
  GATE: "🚪",
  // GÅTT: "",
  GÅVA: "🎁",
  // GAVS: "",
  // GBIT: "",
  // GBPS: "",
  GEEK: "🤓",
  GELÉ: "🍮",
  // GELS: "",
  GEMS: "💎",
  // GENA: "",
  GENI: "🧠",
  // GENS: "",
  // GEST: "",
  GETS: "🐐",
  // GETT: "",
  // GICK: "",
  GIFT: "💍",
  GIGA: "💻",
  GIGG: "🎸",
  // GIGS: "",
  // GIKT: "",
  // GILL: "",
  GINS: "🍸",
  GIPS: "🩹",
  GIRA: "🔄",
  // GIRS: "",
  // GIVA: "",
  // GIVS: "",
  GJUT: "🏗️",
  // GLÄD: "",
  GLAD: "😊",
  GLAM: "✨",
  GLAS: "🥛",
  // GLED: "",
  // GLES: "",
  // GLID: "",
  // GLIM: "",
  GLOB: "🌍",
  GLÖD: "🔥",
  GLÖM: "🧠",
  // GLOR: "",
  // GLOS: "",
  GNAG: "🐀",
  // GNED: "",
  // GNET: "",
  // GNID: "",
  // GNOL: "",
  // GNÖL: "",
  GNOM: "🧙",
  // GNOR: "",
  // GNOS: "",
  // GNUN: "",
  GNUS: "🦬",
  // GNYR: "",
  // GNYS: "",
  // GODA: "",
  GÖDA: "🌱",
  GODA: "😇",
  // GÖDD: "",
  // GODE: "",
  // GODO: "",
  // GODS: "",
  // GÖDS: "",
  GODS: "📦",
  GÖKA: "🐦",
  // GÖKS: "",
  GOLF: "⛳",
  // GÖLS: "",
  GOLV: "🏠",
  GÖMD: "🙈",
  // GOMS: "",
  // GÖMS: "",
  // GÖMT: "",
  // GÖPA: "",
  GÖRA: "🛠️",
  // GÖRE: "",
  // GÖRS: "",
  GOSA: "🤗",
  // GOTS: "",
  // GÖTS: "",
  // GOTT: "",
  // GÖTT: "",
  GOTT: "😋",
  GRÅA: "🩶",
  GRAD: "🌡️",
  // GRÅE: "",
  GRAF: "📈",
  // GRAL: "",
  // GRÄL: "",
  // GRAM: "",
  // GRÄM: "",
  GRAM: "⚖️",
  GRAN: "🌲",
  GRÄS: "🌱",
  // GRÄT: "",
  GRÅT: "😢",
  // GRAV: "",
  GRÄV: "⛏️",
  GRAV: "🪦",
  GREJ: "🧰",
  GREK: "🇬🇷",
  GREN: "🌿",
  // GREP: "",
  GRIN: "😁",
  GRIP: "✊",
  GRIS: "🐷",
  GRÖN: "🟢",
  // GROP: "",
  // GRÖP: "",
  GROP: "🕳️",
  // GROR: "",
  // GROS: "",
  GRÖT: "🥣",
  GROV: "🪵",
  GRUS: "🪨",
  GRYM: "😈",
  GRYN: "🌾",
  // GRYR: "",
  // GRYS: "",
  GRYT: "🍲",
  GUDA: "🙏",
  GUDS: "✝️",
  GULA: "🟡",
  GULD: "🏅",
  // GULE: "",
  GULF: "🌊",
  // GULT: "",
  GUNG: "🎢",
  // GUPP: "",
  GURU: "🧘",
  // GUSS: "",
  GYLF: "👖",
  GYMS: "🏋️",
  HÄCK: "🌳",
  HACK: "💻",
  HÄDA: "🤬",
  HADE: "🕰️",
  // HAFS: "",
  // HAFT: "",
  HAGE: "🐑",
  HÄGG: "🌸",
  // HÄGN: "",
  // HÅGS: "",
  HAHA: "😂",
  HAJA: "🦈",
  HAJP: "📣",
  HAJS: "🦈",
  HAKA: "🪝",
  // HAKE: "",
  // HALA: "",
  HÅLA: "🕳️",
  HALA: "🧊",
  // HALE: "",
  // HALL: "",
  // HÅLL: "",
  // HÄLL: "",
  HÅLL: "✋",
  HALL: "🏛️",
  HÄLL: "🫗",
  HALM: "🌾",
  // HALS: "",
  // HÅLS: "",
  HÄLS: "👋",
  HALS: "👔",
  HALT: "🛑",
  HALV: "🌓",
  HAMN: "⚓",
  HÅNA: "😜",
  // HAND: "",
  // HÄND: "",
  HAND: "✋",
  HÄND: "✋",
  HANE: "♂️",
  // HANG: "",
  // HÄNG: "",
  HANG: "🪂",
  HÄNG: "🪢",
  // HANN: "",
  // HANS: "",
  // HÅNS: "",
  // HÄNT: "",
  HÅRA: "💇",
  // HÅRD: "",
  // HÄRD: "",
  HÅRD: "💪",
  HARE: "🐇",
  // HÄRI: "",
  HARM: "😠",
  HARR: "🐟",
  // HÅRS: "",
  // HÄRS: "",
  // HÅRT: "",
  // HASA: "",
  HASP: "🔒",
  // HAST: "",
  HÄST: "🐴",
  HATA: "💢",
  HATS: "🎩",
  HATT: "🎩",
  // HAVA: "",
  // HÅVA: "",
  // HÄVA: "",
  // HAVA: "",
  HÄVA: "🏋️",
  HÅVA: "🥅",
  // HAVD: "",
  // HÄVD: "",
  // HÅVS: "",
  // HÄVS: "",
  HAVS: "🌊",
  // HÄVT: "",
  HÄXA: "🧙‍♀️",
  HEAT: "🔥",
  // HEDS: "",
  HEHE: "😏",
  HEJA: "🎉",
  HEJD: "🛑",
  HELA: "⭕",
  HELG: "🎉",
  HELT: "💯",
  HEMS: "🏡",
  // HENS: "",
  // HERM: "",
  HERR: "👨",
  // HESA: "",
  // HESE: "",
  // HEST: "",
  HETA: "🔥",
  // HETE: "",
  // HETS: "",
  // HETT: "",
  HIND: "🦌",
  HINK: "🪣",
  // HINN: "",
  // HINT: "",
  HIPP: "🕺",
  // HIRD: "",
  HISS: "🛗",
  HITS: "🎵",
  HIVA: "🫳",
  // HJON: "",
  HJUL: "🛞",
  // HMMM: "",
  HOAR: "🐴",
  // HOAS: "",
  // HOAT: "",
  HÖET: "🌾",
  HÖFT: "🦴",
  HÖGA: "⬆️",
  // HÖGE: "",
  HÖGG: "🪓",
  // HÖGS: "",
  // HÖGT: "",
  HÖJA: "⬆️",
  // HÖJD: "",
  // HOJS: "",
  // HÖJS: "",
  HOJS: "🏍️",
  // HÖJT: "",
  HÖKS: "🦅",
  // HÖLJ: "",
  HOLK: "🐦",
  // HÖLL: "",
  HOMO: "🏳️‍🌈",
  HONA: "♀️",
  HÖNA: "🐔",
  HÖNS: "🐔",
  HOOK: "🪝",
  HOPA: "📚",
  HOPP: "🦘",
  // HOPS: "",
  // HORA: "",
  HÖRA: "👂",
  // HORD: "",
  // HÖRD: "",
  // HORN: "",
  HÖRN: "📐",
  HORN: "📯",
  // HÖRS: "",
  // HÖRT: "",
  // HOSA: "",
  // HOST: "",
  HÖST: "🍂",
  HOST: "🤧",
  HOTA: "⚠️",
  HOTS: "🔥",
  HOVS: "🐎",
  // HSPA: "",
  HTML: "🌐",
  HUDS: "🧴",
  // HUGA: "",
  HUGG: "🪓",
  // HUKA: "",
  // HULD: "",
  // HULL: "",
  // HULT: "",
  HUND: "🐶",
  // HURI: "",
  HUSE: "🏠",
  // HUTU: "",
  HUVA: "🧥",
  // HUVE: "",
  // HUVS: "",
  // HYFS: "",
  // HYMN: "",
  // HYNS: "",
  // HYPA: "",
  HYPE: "📣",
  HYRA: "🏠",
  // HYRD: "",
  // HYRS: "",
  // HYRT: "",
  HYSA: "🏡",
  // HYSS: "",
  // HYST: "",
  HYTT: "🛖",
  ICKE: "🚫",
  IDAG: "📅",
  // IDEL: "",
  // IDEN: "",
  IDÉN: "💡",
  // IDES: "",
  // IDÉS: "",
  // IDET: "",
  // IDKA: "",
  // IDOG: "",
  IDOL: "🌟",
  // IE10: "",
  IFÖR: "👕",
  IGÅR: "⏪",
  IGEL: "🪱",
  IGEN: "🔁",
  IGLO: "🧊",
  IHÅG: "🧠",
  IHOP: "🧩",
  IKLÄ: "👗",
  IKON: "🖼️",
  // ILAR: "",
  // ILAS: "",
  // ILAT: "",
  ILLA: "🤒",
  IMAM: "🕌",
  IMMA: "🌫️",
  IMPA: "😎",
  INÅT: "⬅️",
  INFO: "ℹ️",
  // INGA: "",
  INGÅ: "🚪",
  INGA: "0️⃣",
  // INGE: "",
  // INKL: "",
  INNE: "🏠",
  INOM: "📥",
  INPÅ: "🎯",
  INRE: "🫀",
  INSE: "💡",
  // INTA: "",
  INTE: "❌",
  IPAD: "📱",
  IPOD: "🎵",
  IPV6: "🌐",
  IRIS: "👁️",
  IRRA: "🧭",
  ISÄR: "💔",
  ISAR: "🧊",
  ISAS: "🧊",
  // ISAT: "",
  ISEN: "🧊",
  ISIG: "🧊",
  // ISMS: "",
  // ISNA: "",
  // ISTE: "",
  IVÄG: "🚀",
  IVER: "⚡",
  IVRA: "🏃",
  JABB: "👊",
  // JADÅ: "",
  JAGA: "🏃",
  // JAGS: "",
  JAHA: "💡",
  JAJA: "🙄",
  // JAKT: "",
  JÄKT: "🏃",
  JAKT: "🏹",
  // JAMA: "",
  JÄMN: "⚖️",
  // JÄMT: "",
  // JAPP: "",
  // JARL: "",
  JÄRN: "🔩",
  JÄRV: "🐾",
  // JASÅ: "",
  JÄSA: "🫧",
  JÄST: "🍞",
  // JÄVS: "",
  JAZZ: "🎷",
  JEDI: "⚔️",
  JEEP: "🚙",
  JETS: "✈️",
  JOBB: "💼",
  // JODÅ: "",
  // JODS: "",
  JOJK: "🎶",
  JOJO: "🪀",
  // JONS: "",
  JORD: "🌍",
  JOUR: "📞",
  // JOXA: "",
  // JOXS: "",
  JUDE: "✡️",
  JUDO: "🥋",
  JULI: "☀️",
  JULS: "🎄",
  JUNI: "🌼",
  // JURA: "",
  JURY: "⚖️",
  JUST: "⚖️",
  // KÄCK: "",
  KÅDA: "🌲",
  KAFÉ: "☕",
  KÄFT: "👄",
  KAJA: "🐦",
  // KAJS: "",
  // KÄKA: "",
  KAKA: "🍪",
  KÄKA: "🍽️",
  KÄKE: "🦷",
  KAKI: "🟠",
  // KÅKS: "",
  // KÄKS: "",
  // KALA: "",
  // KALE: "",
  KALK: "🪨",
  KALL: "🥶",
  // KÅLS: "",
  // KALT: "",
  KALV: "🐄",
  KAMP: "⚔️",
  // KAMS: "",
  // KANA: "",
  KÄND: "🌟",
  // KÄNN: "",
  // KANT: "",
  // KÄNT: "",
  KANT: "📐",
  KAOS: "🌪️",
  // KAPA: "",
  // KÅPA: "",
  KAPA: "✂️",
  KÅPA: "🧥",
  // KAPP: "",
  KÄPP: "🦯",
  KAPP: "🧥",
  // KAPS: "",
  // KÅRA: "",
  KÄRA: "❤️",
  // KÄRE: "",
  KARG: "😠",
  // KARL: "",
  KÄRL: "❤️",
  KARL: "👨",
  KARM: "🚪",
  KÄRR: "🛒",
  // KARS: "",
  // KÅRS: "",
  // KART: "",
  KÄRT: "❤️",
  KART: "🍏",
  // KÄRV: "",
  // KASA: "",
  // KASS: "",
  KAST: "🤾",
  KÅTA: "🔥",
  // KÅTE: "",
  // KATS: "",
  KATT: "🐱",
  KAXA: "😎",
  // KÄXS: "",
  KCAL: "🔥",
  // KELA: "",
  // KELS: "",
  KEMI: "🧪",
  KEPS: "🧢",
  KESO: "🧀",
  KEXS: "🍪",
  // KHAT: "",
  KICK: "🦵",
  KIDS: "🧒",
  KIKA: "👀",
  // KILA: "",
  KILO: "⚖️",
  // KILS: "",
  // KIND: "",
  KING: "👑",
  // KISA: "",
  KISS: "🚽",
  KIST: "⚰️",
  // KITT: "",
  // KIVA: "",
  // KIVS: "",
  KJOL: "👗",
  KLÄD: "👕",
  KLÄM: "🤏",
  KLAN: "👥",
  // KLAR: "",
  // KLÅR: "",
  // KLÄR: "",
  KLAR: "✅",
  KLÄR: "👗",
  // KLÅS: "",
  // KLÄS: "",
  // KLEN: "",
  // KLET: "",
  // KLEV: "",
  KLIA: "🖐️",
  // KLIS: "",
  // KLIV: "",
  KLOK: "🧠",
  KLON: "🧬",
  KLOR: "🧪",
  // KLOS: "",
  KLÖS: "🐾",
  KLOT: "⚽",
  // KLÖV: "",
  KLYV: "🪓",
  // KNÄA: "",
  // KNAK: "",
  KNÄN: "🦵",
  // KNÅP: "",
  // KNÄS: "",
  KNAS: "🤪",
  KNÄT: "🦵",
  // KNEP: "",
  KNIP: "🤏",
  KNIV: "🔪",
  KNÖL: "🥔",
  KNOP: "⚓",
  // KNÖS: "",
  // KNÖT: "",
  KNUT: "🪢",
  KNYT: "🪢",
  KÖAR: "🚶‍➡️",
  // KÖAS: "",
  // KÖAT: "",
  KOCK: "👨‍🍳",
  KODA: "💻",
  // KODS: "",
  // KÖER: "",
  KOGG: "⚙️",
  KOJA: "🛖",
  // KOJS: "",
  KOKA: "🍲",
  // KOKS: "",
  KÖKS: "🍳",
  KOKT: "🍲",
  KOLA: "🍬",
  KÖLD: "❄️",
  KOLL: "👀",
  // KOLS: "",
  // KÖLS: "",
  // KOLT: "",
  KOLV: "🔫",
  KOMA: "😴",
  // KOMB: "",
  KOMP: "🎸",
  // KOMS: "",
  KONA: "🔺",
  // KONS: "",
  KÖNS: "⚧️",
  KÖPA: "🛍️",
  KOPP: "☕",
  KÖPS: "🛒",
  // KOPT: "",
  // KÖPT: "",
  // KORA: "",
  KÖRA: "🚗",
  // KÖRD: "",
  KORG: "🧺",
  KORK: "🍾",
  KORN: "🌾",
  KORP: "🐦‍⬛",
  // KORS: "",
  // KÖRS: "",
  KORS: "✝️",
  // KÖRT: "",
  KORT: "🃏",
  KORV: "🌭",
  // KOSA: "",
  KOST: "🍽️",
  KÖTT: "🥩",
  // KOXA: "",
  // KRÄK: "",
  KRÅK: "🐦",
  KRÄK: "🤮",
  // KRÄM: "",
  KRAM: "🤗",
  KRÄM: "🧴",
  KRAN: "🚰",
  // KRAS: "",
  // KRÅS: "",
  // KRAV: "",
  // KRÄV: "",
  KRAV: "📋",
  KRAX: "🐦‍⬛",
  KRIA: "📝",
  KRIG: "⚔️",
  KRIS: "🚨",
  // KRIT: "",
  KROG: "🍺",
  // KROK: "",
  KRÖK: "↪️",
  KROK: "🪝",
  KROM: "✨",
  // KRÖN: "",
  // KRÖP: "",
  // KRUM: "",
  KRUS: "🏺",
  KRUT: "💥",
  // KRUX: "",
  KRYA: "❤️‍🩹",
  KRYP: "🐛",
  KUBB: "🪵",
  KUBS: "🧊",
  KUDD: "🛌",
  // KUFS: "",
  KUGG: "⚙️",
  KUKS: "🍆",
  KULA: "⚪",
  KULL: "🐣",
  KULT: "🛐",
  KUND: "🛒",
  KUNG: "🤴",
  KUPA: "🐝",
  KUPÉ: "🚆",
  KUPP: "♟️",
  // KURA: "",
  // KURD: "",
  // KURR: "",
  KURS: "📚",
  // KUSE: "",
  KUSK: "🐎",
  KUST: "🏖️",
  KUTA: "🏃",
  // KUVA: "",
  KVAL: "😖",
  KVAR: "📍",
  // KVÄS: "",
  KVAV: "🥵",
  KVÄV: "🫁",
  // KVED: "",
  // KVID: "",
  KVOT: "➗",
  KYLA: "🥶",
  KYLD: "🥶",
  // KYLS: "",
  // KYLT: "",
  // KYSK: "",
  KYSS: "💋",
  LABB: "🧪",
  // LÄCK: "",
  LACK: "💅",
  LÄCK: "💧",
  LÅDA: "📦",
  LADA: "🛖",
  // LADE: "",
  // LAGA: "",
  LÅGA: "🔥",
  LAGA: "🔧",
  // LAGD: "",
  // LÅGE: "",
  LÄGE: "📍",
  // LAGG: "",
  // LÄGG: "",
  LAGG: "🎿",
  LÄGG: "🫳",
  // LAGS: "",
  // LAGT: "",
  // LÅGT: "",
  LAJV: "🎤",
  // LAKA: "",
  // LÄKA: "",
  LAKA: "🧺",
  LÄKA: "🩹",
  // LÄKE: "",
  // LÄKS: "",
  // LÄKT: "",
  // LALL: "",
  LAMA: "🦙",
  // LAME: "",
  LAMM: "🐑",
  // LAMT: "",
  LÅNA: "💳",
  LAND: "🗺️",
  LÅNE: "🏦",
  LÅNG: "📏",
  LÄNK: "🔗",
  // LANS: "",
  // LÅNS: "",
  // LÄNS: "",
  // LAPA: "",
  // LAPD: "",
  // LAPP: "",
  LÄPP: "👄",
  LAPP: "📄",
  LÄRA: "📚",
  // LÄRD: "",
  LARM: "🚨",
  // LÄRO: "",
  // LÅRS: "",
  // LÄRS: "",
  // LÄRT: "",
  LARV: "🐛",
  LÄSA: "📖",
  LÅSA: "🔒",
  LÄSK: "🥤",
  LASS: "🚚",
  // LAST: "",
  // LÅST: "",
  // LÄST: "",
  LÅST: "🔒",
  // LATA: "",
  LÅTA: "🔊",
  LATA: "🦥",
  // LATE: "",
  // LÄTE: "",
  // LÅTS: "",
  // LÄTS: "",
  LÄTT: "🪶",
  LAVA: "🌋",
  LAVS: "🌿",
  LÄXA: "📝",
  LCHF: "🥩",
  LEDA: "🧭",
  // LEDD: "",
  LEDS: "😢",
  LEGO: "🧱",
  // LEJA: "",
  // LEJD: "",
  // LEJS: "",
  // LEJT: "",
  LEKA: "🧸",
  LEKS: "🧸",
  // LEKT: "",
  // LEMS: "",
  // LENA: "",
  // LENT: "",
  LERA: "🏺",
  // LESS: "",
  LETA: "🔍",
  // LETT: "",
  LEVA: "❤️",
  // LEVD: "",
  // LEVE: "",
  // LEVS: "",
  // LEVT: "",
  // LIAN: "",
  // LIAR: "",
  // LIDA: "",
  // LIDS: "",
  // LIEN: "",
  // LIES: "",
  LIFT: "🏋️",
  LIGA: "⚽",
  // LIGG: "",
  // LIKA: "",
  // LIKE: "",
  // LIKS: "",
  // LIKT: "",
  LILA: "🟣",
  // LILL: "",
  LIME: "🍋",
  // LIMS: "",
  LINA: "🧵",
  LIND: "🌳",
  LINS: "📷",
  LIPA: "😭",
  LIRA: "🎸",
  // LIRE: "",
  // LIST: "",
  // LITA: "",
  // LITE: "",
  LIVA: "🎉",
  LIVE: "🔴",
  // LIVS: "",
  // LJÖD: "",
  // LJÖG: "",
  // LJÖT: "",
  LJUD: "🔊",
  LJUG: "🤥",
  LJUM: "🌡️",
  LJUS: "💡",
  // LJUT: "",
  LJUV: "😍",
  // LKPG: "",
  LOBB: "🏨",
  // LOBS: "",
  LOCK: "🫙",
  LÖDA: "🔥",
  // LÖDD: "",
  // LÖDS: "",
  LOFT: "🏠",
  // LÖGA: "",
  LOGE: "🎭",
  LOGG: "📓",
  LOGI: "🏠",
  LÖGN: "🤥",
  LOGO: "🖌️",
  // LOGS: "",
  // LOJA: "",
  LÖJA: "🐟",
  // LOJE: "",
  // LÖJE: "",
  // LOJT: "",
  // LOKS: "",
  LÖKS: "🧅",
  // LOMA: "",
  // LÖNA: "",
  LÖNN: "🌳",
  // LÖNS: "",
  // LÖNT: "",
  LOOK: "👀",
  LOOP: "🔁",
  LÖPA: "🏃",
  LOPP: "🏃",
  LÖPS: "🏃",
  // LÖPT: "",
  LORD: "🤵",
  LORT: "💩",
  LÖSA: "🔓",
  // LÖSE: "",
  // LOSS: "",
  // LÖSS: "",
  LOSS: "⚓",
  LÖSS: "🪳",
  // LÖST: "",
  // LOTS: "",
  // LOTT: "",
  // LÖTT: "",
  LOTT: "🎟️",
  // LOVA: "",
  LÖVA: "🍃",
  LOVA: "🤞",
  // LOVS: "",
  LÖVS: "🍂",
  LUDD: "🧸",
  LUFT: "💨",
  LUGG: "💇",
  LUGN: "😌",
  LUKT: "👃",
  LUND: "🌳",
  // LUNS: "",
  LUPP: "🔍",
  LURA: "🎣",
  // LURS: "",
  LURT: "🤔",
  LUST: "🔥",
  LUTA: "🎸",
  // LUTS: "",
  LUVA: "🧢",
  // LYAN: "",
  // LYAS: "",
  LYDA: "🫡",
  // LYDD: "",
  // LYDS: "",
  LYFT: "🏋️",
  // LYOR: "",
  LYRA: "🎵",
  LYSA: "💡",
  // LYSE: "",
  // LYST: "",
  LYTE: "♿",
  // LYTT: "",
  LYXA: "💎",
  MACK: "⛽",
  // MADS: "",
  // MÅFÅ: "",
  MAGE: "🤰",
  MAGI: "🪄",
  // MÅGS: "",
  // MÄHÄ: "",
  MAIL: "✉️",
  MAJS: "🌽",
  MAKA: "👩‍❤️‍👨",
  MAKE: "👨‍❤️‍👩",
  MAKT: "👑",
  MALA: "⚙️",
  MÅLA: "🎨",
  // MALD: "",
  MALL: "📄",
  MALM: "⛏️",
  // MALS: "",
  MÅLS: "🥅",
  // MALT: "",
  // MANA: "",
  MÅNA: "🌙",
  MANA: "📣",
  MÅNE: "🌙",
  MANI: "🤪",
  // MANS: "",
  // MÅNS: "",
  // MÄNS: "",
  // MÅNT: "",
  MAPP: "📁",
  MARA: "😈",
  MÅRD: "🦡",
  MÄRG: "🦴",
  // MARK: "",
  // MÄRK: "",
  MARK: "🌍",
  MÄRK: "🏷️",
  MÄRR: "🐎",
  MARS: "🪐🍫",
  // MASA: "",
  // MÄSK: "",
  MASK: "🎭",
  // MASS: "",
  MAST: "⛵",
  MÅST: "✅",
  // MATA: "",
  // MÄTA: "",
  MATA: "🍽️",
  MÄTA: "📏",
  // MATS: "",
  // MÄTS: "",
  MATS: "🍱",
  // MATT: "",
  // MÅTT: "",
  // MÄTT: "",
  MATT: "🧹",
  MAXA: "⬆️",
  MBIT: "💾",
  MBPS: "🌐",
  MDMA: "💊",
  // MDPV: "",
  // MEDE: "",
  // MEDS: "",
  MEGA: "📢",
  // MEJA: "",
  MEJL: "📧",
  MEKA: "🔧",
  MEMO: "📝",
  // MEMS: "",
  // MENA: "",
  // MENS: "",
  // MENT: "",
  MENY: "📋",
  // MERA: "",
  // MESA: "",
  // MEST: "",
  META: "🎣",
  MICK: "🎤",
  MILD: "🌤️",
  // MILS: "",
  // MILT: "",
  // MIMA: "",
  // MINA: "",
  // MINI: "",
  MINK: "🐾",
  // MINN: "",
  // MINS: "",
  MINT: "🌿",
  MISS: "❌",
  MIST: "🌫️",
  // MITT: "",
  MIXA: "🎛️",
  MJÖD: "🍺",
  MJÖL: "🌾",
  MJUK: "🧸",
  MOBB: "👥",
  MÖDA: "😓",
  // MODD: "",
  MODE: "👗",
  // MODS: "",
  // MÖGS: "",
  // MOJA: "",
  // MOJS: "",
  // MOJT: "",
  // MOLA: "",
  MOLN: "☁️",
  MOMS: "🧾",
  // MÖNS: "",
  MOPP: "🧹",
  MOPS: "🐕",
  // MÖRA: "",
  MORD: "🔪",
  // MÖRE: "",
  MÖRK: "🌑",
  // MORS: "",
  // MÖRS: "",
  MÖRT: "🐟",
  MOSA: "🥔",
  MÖSS: "🐁",
  // MOTA: "",
  MÖTA: "🤝",
  MOTA: "🛡️",
  MÖTE: "🗣️",
  // MÖTS: "",
  // MOTT: "",
  // MÖTT: "",
  MOTT: "📥",
  MUDD: "🪨",
  MUGG: "☕",
  MULA: "🫏",
  // MULE: "",
  MUMS: "😋",
  MUNK: "🍩",
  MUNS: "👄",
  // MUPP: "",
  MURA: "🧱",
  // MURS: "",
  MUSA: "🎨",
  MUST: "🧃",
  MUTA: "💰",
  MYGG: "🦟",
  MYNT: "🪙",
  MYRA: "🐜",
  MYRS: "🐜",
  MYSA: "🛋️",
  MYSK: "🦌",
  MYST: "🥰",
  MYTS: "📖",
  // NABB: "",
  NÄBB: "🐦",
  // NÅDD: "",
  // NÅDE: "",
  // NÅDS: "",
  // NAFS: "",
  // NÄHÄ: "",
  // NÄHE: "",
  NAIV: "👶",
  // NAJA: "",
  // NÅJA: "",
  NÅLA: "🪡",
  // NÅLS: "",
  // NAMN: "",
  NÄMN: "🗣️",
  NAMN: "🪪",
  // NÄNÄ: "",
  // NÅNS: "",
  NAPP: "👶",
  // NÄPS: "",
  // NÅRA: "",
  NÄRA: "📍",
  // NÄRD: "",
  // NARE: "",
  // NARR: "",
  // NÄRS: "",
  // NÄRT: "",
  NÄSA: "👃",
  NÄST: "⏭️",
  NÄTA: "🕸️",
  // NÄTS: "",
  // NÅTT: "",
  // NÄTT: "",
  NATT: "🌙",
  NÄVE: "✊",
  NAVS: "🧭",
  // NEGS: "",
  // NEJD: "",
  // NEJS: "",
  // NEKA: "",
  NEON: "💡",
  // NERE: "",
  NERV: "🧠",
  NEVÖ: "🧑",
  NIAN: "9️⃣",
  // NIAS: "",
  NICK: "🙇",
  NIGA: "🙇‍♀️",
  // NIGS: "",
  // NIOB: "",
  // NIOR: "",
  // NIOS: "",
  NITA: "🔩",
  // NITS: "",
  NIVÅ: "📊",
  // NJAE: "",
  // NJÖT: "",
  NJUR: "🫘",
  NJUT: "😌",
  NOCK: "🏠",
  NÖDD: "🆘",
  // NODS: "",
  // NÖDS: "",
  NÖFF: "🐷",
  NOGA: "🔍",
  // NOJA: "",
  NÖJA: "😊",
  NOJA: "😰",
  NÖJD: "😌",
  NÖJE: "🎭",
  // NÖJS: "",
  // NÖJT: "",
  NOLL: "0️⃣",
  // NÖPS: "",
  NORD: "❄️",
  NÖRD: "🤓",
  NORM: "📏",
  NORR: "⬆️",
  // NORS: "",
  NOSA: "👃",
  // NOTA: "",
  NÖTA: "🧠",
  NOTA: "🧾",
  // NOTS: "",
  // NÖTS: "",
  // NÖTT: "",
  NOVA: "💥",
  NUBB: "📌",
  NUET: "⏱️",
  // NUNA: "",
  NYÅR: "🎆",
  NYCK: "🔑",
  NYMF: "🧚",
  NYPA: "🤏",
  // NYPS: "",
  // NYPT: "",
  // NYSA: "",
  // NYSS: "",
  // NYST: "",
  NYTT: "🆕",
  ODDS: "🎲",
  ODEN: "🧙",
  // ODES: "",
  // ODET: "",
  ODLA: "🌱",
  ODÖD: "🧟",
  ODÖR: "💨",
  OFIN: "👎",
  OFOG: "⚠️",
  OFRI: "🔒",
  OFTA: "🔁",
  OGIN: "😒",
  // OJAR: "",
  // OJAS: "",
  // OJAT: "",
  OJOJ: "😮",
  OKAY: "👌",
  OKEJ: "👌",
  // OKEN: "",
  // OKET: "",
  // OKEY: "",
  // OLAT: "",
  // OLÅT: "",
  OLED: "🖥️",
  // OLIK: "",
  OLIV: "🫒",
  OLJA: "🛢️",
  OLJE: "🛢️",
  // OLLE: "",
  // OMAK: "",
  // OMBE: "",
  OMEN: "🔮",
  // OMGE: "",
  // OMSE: "",
  // ONÅD: "",
  ONDA: "😈",
  ONDE: "😈",
  // ONDO: "",
  ONYX: "⚫",
  // OÖMT: "",
  OPAL: "💎",
  OPEL: "🚗",
  // ORÅD: "",
  ORAL: "👄",
  ORDA: "🗣️",
  // ORDF: "",
  ORDS: "💬",
  // OREN: "",
  ORKA: "💪",
  // ORKS: "",
  ORMA: "🐍",
  // ORMS: "",
  OROA: "😟",
  ORON: "😟",
  OROS: "😟",
  // ORTS: "",
  // OSAR: "",
  // OSAT: "",
  // OSED: "",
  OSIG: "💨",
  OSTS: "🧀",
  // OTAL: "",
  OTID: "⏰",
  OTRO: "💔",
  OTTA: "🌅",
  // OTUR: "",
  OTYG: "👹",
  OUTA: "🏳️‍🌈",
  OVAL: "🥚",
  // OVAN: "",
  // OVÄN: "",
  OVAN: "⬆️",
  OVÄN: "😠",
  OVIG: "🤕",
  OXAR: "🐂",
  OXEN: "🐂",
  // OXES: "",
  OZON: "🌍",
  PACK: "📦",
  PAFF: "😲",
  PÅGÅ: "▶️",
  PAJA: "💥",
  PAJS: "🤡",
  // PÅKS: "",
  PAKT: "🤝",
  PÅLE: "🪵",
  PALL: "🪑",
  PALM: "🌴",
  PÄLS: "🧥",
  // PALT: "",
  PAMP: "🎩",
  PANK: "💸",
  PANT: "♻️",
  PAPP: "📦",
  PARA: "💰",
  // PARI: "",
  PARK: "🌳",
  PÄRM: "📒",
  // PARS: "",
  PART: "🧩",
  PÅSE: "🛍️",
  PÅSK: "🐣",
  PASS: "🛂",
  // PÅTA: "",
  PATÉ: "🍖",
  PATT: "🍈",
  PAUS: "⏸️",
  PÅVE: "✝️",
  // PCIE: "",
  PEAK: "🏔️",
  PEJL: "📡",
  PEKA: "👉",
  PENG: "💰",
  PENN: "🖊️",
  PEPP: "💪",
  // PEPS: "",
  PEST: "🦠",
  PETA: "👉",
  // PIET: "",
  PIFF: "✨",
  PIGA: "👩‍🌾",
  PIGG: "⚡",
  PIKA: "😠",
  // PIKÉ: "",
  // PIKS: "",
  // PILA: "",
  PILK: "🎣",
  PILS: "🍺",
  PINA: "😫",
  PINS: "📌",
  PION: "🌸",
  PIPA: "🪈",
  PIPS: "🐣",
  PIRR: "😬",
  // PIRS: "",
  // PISK: "",
  PISS: "🚽",
  PIST: "🎿",
  PJÄS: "♟️",
  PLÄD: "🧣",
  // PLAN: "",
  PLÅN: "👛",
  PLAN: "📋",
  PLÅT: "🔩",
  PLOG: "🚜",
  PLÖJ: "🚜",
  // PLÖS: "",
  PLUS: "➕",
  PLYM: "🪶",
  PODD: "🎙️",
  POEM: "📜",
  POET: "✍️",
  POFF: "💨",
  // POJK: "",
  // PÖJK: "",
  POJK: "👦",
  PÖJK: "👦",
  POLO: "🐎",
  // POLS: "",
  PÖLS: "🌭",
  POOL: "🏊",
  POPS: "🍭",
  PORR: "🔞",
  // PORS: "",
  PORT: "🚪",
  // PÖSA: "",
  POSE: "🕺",
  // POST: "",
  // PÖST: "",
  POST: "📮",
  POTT: "🚽",
  PRÅL: "💎",
  PRÅM: "⛴️",
  PRAO: "🧑‍💼",
  PRAT: "💬",
  PRIS: "🏆",
  // PROV: "",
  // PRÖV: "",
  PROV: "📝",
  PRÖV: "🧪",
  PRYA: "🧑‍💼",
  PRYD: "🎀",
  PRYL: "🔧",
  PSYK: "🧠",
  PUBS: "🍺",
  PUCK: "🏒",
  PUFF: "💨",
  PUKA: "🥁",
  PULS: "💓",
  PUMA: "🐆",
  PUMP: "⛽",
  PUND: "💷",
  PUNG: "👝",
  PUNK: "🤘",
  // PURA: "",
  // PURT: "",
  PUSS: "😘",
  PUST: "😮‍💨",
  PUTA: "🫸",
  // PUTS: "",
  PUTT: "⛳",
  PYNT: "🎄",
  PYRA: "🔥",
  // PYRT: "",
  PYSA: "💨",
  // PYST: "",
  // PYTT: "",
  QUIZ: "❓",
  RACE: "🏁",
  // RACK: "",
  RÄCK: "✋",
  RACK: "🗄️",
  // RADA: "",
  RÅDA: "💡",
  RADA: "📏",
  // RÅDD: "",
  RÄDD: "😱",
  // RADS: "",
  // RÅDS: "",
  RÄDS: "😨",
  // RAFS: "",
  RÅGA: "🌾",
  // RÅGE: "",
  RAGG: "💇",
  // RÅGS: "",
  RAID: "🛡️",
  // RAKA: "",
  // RÅKA: "",
  RÄKA: "🍤",
  RÅKA: "🐦",
  RAKA: "🪒",
  // RAKE: "",
  // RÅKS: "",
  // RAKT: "",
  RÄLS: "🛤️",
  // RAMA: "",
  // RÅMA: "",
  RAMA: "🖼️",
  RAMP: "🛹",
  // RAMS: "",
  // RANA: "",
  RÅNA: "🥷",
  RAND: "➖",
  RANG: "🏅",
  RANK: "🤢",
  // RANN: "",
  // RÄNN: "",
  // RÅNS: "",
  // RÄNT: "",
  RAPA: "🫧",
  RAPP: "🎤",
  RAPS: "🌼",
  RARA: "💕",
  // RARE: "",
  // RART: "",
  RASA: "💥",
  // RASK: "",
  RASP: "🗜️",
  RAST: "☕",
  // RATA: "",
  RÄTA: "📏",
  // RATT: "",
  RÄTT: "✅",
  RÅTT: "🥩",
  RATT: "🚗",
  RÄVS: "🦊",
  READ: "📖",
  REAL: "💯",
  REAN: "🏷️",
  REAR: "🏷️",
  // REAS: "",
  // REAT: "",
  REDA: "✅",
  REDD: "🛟",
  REDO: "✅",
  // REDS: "",
  REGI: "🎬",
  REGN: "🌧️",
  REKA: "👀",
  RELÄ: "🔌",
  REMI: "🎴",
  REMS: "🧵",
  RENA: "🧼",
  // RENE: "",
  // RENS: "",
  // RENT: "",
  REOR: "🛍️",
  REPA: "🪢",
  // REPS: "",
  RESA: "✈️",
  // RESE: "",
  REST: "➗",
  RETA: "😜",
  // RETT: "",
  REVA: "🐾",
  // REVS: "",
  REVY: "🎭",
  RIAL: "💰",
  RIDÅ: "🎭",
  RIDA: "🐎",
  // RIDS: "",
  RIFF: "🎸",
  RIGG: "⚙️",
  RIKA: "💰",
  RIKE: "👑",
  // RIKT: "",
  // RIMS: "",
  RING: "💍",
  RINK: "⛸️",
  // RINN: "",
  RIPA: "🐦",
  RISK: "⚠️",
  RITA: "✏️",
  RITS: "📐",
  // RITT: "",
  RIVA: "🧻",
  // RIVS: "",
  ROAD: "🛣️",
  ROAR: "😄",
  // ROAS: "",
  // ROAT: "",
  ROCK: "🎸",
  RÖDA: "🔴",
  RODD: "🚣",
  // RÖDE: "",
  RÖJA: "🧹",
  // RÖJD: "",
  // RÖJS: "",
  // RÖJT: "",
  RÖKA: "🚬",
  RÖKS: "🚬",
  RÖKT: "🥓",
  ROLL: "🎲",
  // ROMB: "",
  ROMS: "🐟",
  // RÖNA: "",
  ROND: "🔄",
  RÖNN: "🌳",
  // RÖNS: "",
  // RÖNT: "",
  ROPA: "📢",
  // ROPS: "",
  RÖRA: "🌀",
  // RÖRD: "",
  // RÖRS: "",
  // RÖRT: "",
  ROSA: "🌹",
  // ROST: "",
  // RÖST: "",
  ROST: "🍞",
  RÖST: "🗳️",
  // ROTA: "",
  // RÖTA: "",
  ROTA: "🌱",
  RÖTA: "🦠",
  // ROTS: "",
  // RÖTS: "",
  // ROTT: "",
  RÖTT: "🔴",
  // ROVA: "",
  RÖVA: "🥷",
  // ROVS: "",
  // RÖVS: "",
  // RUBB: "",
  RUFF: "⛵",
  RUGG: "🌧️",
  RUIN: "🏚️",
  RUMP: "🍑",
  RUMS: "🛏️",
  RUNA: "ᚱ",
  RUND: "⚪",
  RUNT: "🔄",
  RUSA: "🏃",
  RUSH: "⚡",
  RUSK: "🌧️",
  RUTA: "🪟",
  // RUTT: "",
  RUVA: "🪺",
  RYCK: "🫨",
  RYGG: "🔙",
  RYKA: "💨",
  // RYKS: "",
  // RYKT: "",
  RYMD: "🌌",
  // RYMS: "",
  // RYMT: "",
  RYSA: "🥶",
  RYSK: "🇷🇺",
  RYSS: "🇷🇺",
  // RYST: "",
  RYTA: "🦁",
  RYTM: "🥁",
  // RYTS: "",
  SAAB: "🚗",
  SÄCK: "🎒",
  SÅDD: "🌱",
  // SADE: "",
  // SÄDS: "",
  SAFT: "🧃",
  // SAGA: "",
  // SÅGA: "",
  // SÄGA: "",
  SAGA: "📖",
  SÄGA: "🗣️",
  SÅGA: "🪚",
  // SAGD: "",
  // SÅGS: "",
  // SÄGS: "",
  // SAGT: "",
  // SÄJA: "",
  // SÄJS: "",
  SAJT: "🌐",
  // SAKE: "",
  // SAKS: "",
  SÅLD: "💰",
  SÄLJ: "🏷️",
  // SÅLL: "",
  // SÄLL: "",
  // SALS: "",
  SÄLS: "🦭",
  // SÅLT: "",
  SALT: "🧂",
  // SALU: "",
  SAME: "🧑",
  // SAMS: "",
  // SAMT: "",
  // SÅNA: "",
  // SÄND: "",
  SAND: "🏖️",
  SÄND: "📤",
  SÅNG: "🎵",
  SÄNG: "🛏️",
  // SANK: "",
  // SÄNK: "",
  SANK: "⚓",
  SÄNK: "⬇️",
  SANN: "✅",
  // SANS: "",
  // SANT: "",
  // SÅNT: "",
  // SÄNT: "",
  SÅPA: "🧼",
  // SÅRA: "",
  // SÄRA: "",
  SÅRA: "🩸",
  // SARG: "",
  SÄRK: "👕",
  // SARS: "",
  // SÅRS: "",
  SARS: "🦠",
  // SÅTA: "",
  // SÅTE: "",
  SÄTE: "💺",
  SATS: "🎯",
  // SATT: "",
  // SÅTT: "",
  // SÄTT: "",
  // SAVS: "",
  SAXA: "✂️",
  SCEN: "🎭",
  // SDHC: "",
  // SDXC: "",
  SEDD: "👀",
  // SEDS: "",
  // SEGA: "",
  // SEGE: "",
  // SEGT: "",
  SEJM: "🐟",
  SEKT: "🏛️",
  // SELE: "",
  SEMI: "↔️",
  // SENA: "",
  // SENE: "",
  // SENT: "",
  SERB: "🇷🇸",
  // SETS: "",
  // SETT: "",
  SEXA: "6️⃣",
  // SEXT: "",
  SFÄR: "🌐",
  SHOP: "🛍️",
  SHOW: "🎭",
  // SIAR: "",
  // SIAS: "",
  // SIAT: "",
  SIDA: "📄",
  // SIDO: "",
  // SIKH: "",
  // SIKS: "",
  SIKT: "🎯",
  // SILA: "",
  SILL: "🐟",
  SILO: "🌾",
  // SILS: "",
  SIMS: "🎮",
  // SINA: "",
  SIPP: "🥤",
  // SISA: "",
  SIST: "🔚",
  // SITA: "",
  SITS: "🪑",
  // SITT: "",
  // SJAL: "",
  SJÄL: "👻",
  SJAL: "🧣",
  // SJÅP: "",
  // SJÅS: "",
  SJÖD: "🍲",
  // SJOK: "",
  SJÖN: "🌊",
  SJÖS: "🚢🌊",
  SJUA: "7️⃣",
  SJUD: "♨️",
  SJUK: "🤒",
  SJUS: "7️⃣",
  // SKAL: "",
  // SKÅL: "",
  SKÄL: "⚖️",
  SKAL: "🐚",
  SKÅL: "🥂",
  // SKAM: "",
  // SKÄM: "",
  SKAM: "😳",
  SKÅP: "🗄️",
  // SKAR: "",
  SKÄR: "🔪",
  SKAV: "🩹",
  SKED: "🥄",
  SKEN: "✨",
  // SKER: "",
  SKET: "💩",
  // SKEV: "",
  SKID: "🎿",
  SKIN: "✨",
  // SKIR: "",
  SKIT: "💩",
  SKIV: "💿",
  SKOG: "🌲🌳",
  SKOJ: "😄",
  SKOL: "🏫",
  // SKON: "",
  SKÖN: "😌",
  // SKOP: "",
  // SKÖR: "",
  SKOR: "👟",
  SKÖR: "🫧",
  // SKOS: "",
  SKÖT: "🔫",
  SKRÅ: "🧰",
  SKRI: "😱",
  SKUM: "🫧",
  SKUR: "🌧️",
  SKUT: "⛵",
  // SKYL: "",
  // SKYM: "",
  SKYN: "☁️",
  // SKYR: "",
  // SKYS: "",
  // SLAF: "",
  SLAG: "🥊",
  // SLAK: "",
  SLAM: "🎤",
  // SLÅN: "",
  SLÄP: "🚛",
  SLÅR: "👊",
  // SLAS: "",
  // SLÅS: "",
  // SLÄT: "",
  SLAV: "⛓️",
  SLEM: "🤢",
  // SLET: "",
  SLEV: "🥄",
  SLIT: "💪",
  SLÖA: "🦥",
  // SLÖE: "",
  SLOG: "👊",
  // SLÖK: "",
  // SLÖT: "",
  SLUG: "🦊",
  SLUM: "🏚️",
  SLUT: "🔚",
  SMAK: "👅",
  SMAL: "📏",
  // SMÅÖ: "",
  SMED: "🔨",
  SMEK: "🫳",
  SMET: "🧈",
  // SMID: "",
  SMIT: "🏃",
  // SMOG: "",
  // SMÖG: "",
  SMOG: "🌫️",
  SMÖR: "🧈",
  SMYG: "🥷",
  SNÅL: "💰",
  // SNAR: "",
  SNÅR: "🌿",
  // SNÄS: "",
  SNÄV: "↔️",
  // SNEA: "",
  SNED: "↗️",
  // SNES: "",
  SNÖA: "❄️",
  SNOK: "🔍",
  SNÖN: "❄️",
  // SNOR: "",
  // SNÖR: "",
  SNOR: "🤧",
  SNÖR: "🧵",
  // SNOS: "",
  SNÖS: "❄️",
  SNÖT: "🤧",
  SNUS: "👄",
  SNUT: "👮",
  SNYT: "🤧",
  SOFF: "🛋️",
  SOFT: "🧸",
  // SÖGS: "",
  SOJA: "🫘",
  SÖKA: "🔍",
  // SÖKS: "",
  // SÖKT: "",
  // SÖLA: "",
  SOLA: "☀️",
  SOLO: "🧍",
  // SOLS: "",
  SÖMN: "😴",
  // SÖMS: "",
  // SONA: "",
  // SOND: "",
  SONS: "👦",
  SOPA: "🧹",
  // SÖPS: "",
  SORG: "💔",
  SÖRJ: "😢",
  SORK: "🐭",
  // SORL: "",
  SORT: "🗂️",
  // SOSS: "",
  // SOTA: "",
  SÖTA: "🍬",
  // SÖTE: "",
  // SOTS: "",
  // SÖTT: "",
  SOUL: "🎵",
  // SÖVA: "",
  SOVA: "😴",
  SÖVA: "😴",
  // SÖVD: "",
  // SOVS: "",
  // SÖVS: "",
  SOVS: "😴",
  // SÖVT: "",
  SPÄD: "👶",
  // SPAK: "",
  // SPÄK: "",
  SPAK: "🎮",
  SPAM: "📧",
  // SPAN: "",
  SPÅN: "🪵",
  // SPAR: "",
  // SPÅR: "",
  // SPÄR: "",
  SPÅR: "🐾",
  SPAR: "💰",
  // SPAS: "",
  // SPÅS: "",
  // SPÄS: "",
  SPAS: "🧖",
  SPAT: "♠️",
  // SPCS: "",
  SPEL: "🎮",
  SPEX: "🎭",
  SPIK: "🔨",
  SPIS: "🔥",
  SPÖA: "👊",
  SPÖK: "👻",
  SPÖN: "🪄",
  // SPOR: "",
  // SPÖS: "",
  // SPÖT: "",
  SPYA: "🤮",
  SPYR: "🤮",
  SPYS: "🤮",
  // STÄA: "",
  STAB: "👥",
  STAD: "🏙️",
  STÄD: "🧹",
  // STAL: "",
  // STÅL: "",
  STAL: "🥷",
  STÅL: "🔩",
  // STAM: "",
  // STÄM: "",
  STAM: "🌳",
  STÄM: "🎵",
  STAN: "🏙️",
  STÅR: "🧍",
  // STÅS: "",
  // STAT: "",
  // STÅT: "",
  STAT: "🏛️",
  // STAV: "",
  // STÄV: "",
  STAV: "🦯",
  // STCC: "",
  STEG: "👣",
  STEK: "🥩",
  STEL: "🧍",
  STEN: "🪨",
  STIA: "🐖",
  STIG: "🛤️",
  STIL: "👗",
  STIM: "🐟",
  // STOD: "",
  // STÖD: "",
  STOD: "🧍",
  STÖD: "🩼",
  STOJ: "📣",
  STÖK: "🧹",
  STOL: "🪑",
  // STON: "",
  STÖN: "😩",
  // STÖP: "",
  STOP: "🍺",
  // STOR: "",
  // STÖR: "",
  STOR: "🐘",
  STÖR: "🔊",
  // STOS: "",
  STÖT: "💥",
  STRÅ: "🌾",
  STRÖ: "🧂",
  // STUG: "",
  // STUK: "",
  STUM: "🤐",
  STUP: "🏔️",
  STYR: "🚗",
  STYV: "📏",
  SUCK: "😮‍💨",
  SUDD: "✏️",
  SUGA: "🥤",
  // SUGS: "",
  SULA: "👞",
  SUMP: "🐸",
  SUND: "🏖️",
  // SUNT: "",
  SUPA: "🍺",
  SUPÉ: "🍽️",
  // SUPS: "",
  SURA: "😠",
  // SURE: "",
  SURF: "🏄",
  SURR: "🐝",
  // SURT: "",
  SUSA: "💨",
  SUVS: "🚙",
  SVAG: "🪶",
  SVAJ: "🌬️",
  // SVAL: "",
  // SVÅL: "",
  SVAL: "🧊",
  SVAN: "🦢",
  // SVAR: "",
  // SVÅR: "",
  SVÄR: "⚔️",
  SVAR: "💬",
  SVÅR: "🧩",
  // SVED: "",
  SVEK: "💔",
  SVEP: "🌪️",
  SVID: "🔥",
  SVIK: "💔",
  SVIN: "🐖",
  SVIT: "🏨",
  SVOR: "🤬",
  SYDD: "🪡",
  SYDÖ: "🏝️",
  // SYDS: "",
  // SYLS: "",
  SYLT: "🍓",
  SYNA: "👀",
  SYND: "😈",
  // SYNE: "",
  SYNK: "🔄",
  // SYNS: "",
  // SYNT: "",
  SYRA: "🧪",
  SYRE: "🫁",
  // SYTT: "",
  TABB: "❌",
  TABU: "🚫",
  // TÄCK: "",
  TACK: "🙏",
  TÄCK: "🛏️",
  TACO: "🌮",
  TAFS: "🫳",
  // TAGA: "",
  TÅGA: "🚶",
  TAGG: "🏷️",
  // TAGS: "",
  TÅGS: "🚆",
  TAJT: "👖",
  TAKS: "🏠",
  // TAKT: "",
  // TÄKT: "",
  TAKT: "🎵",
  // TALA: "",
  TÅLA: "💪",
  TALA: "🗣️",
  // TÅLD: "",
  // TALG: "",
  TÄLJ: "🔪",
  TALL: "🌲",
  // TALS: "",
  // TÅLS: "",
  // TALT: "",
  // TÅLT: "",
  TÄLT: "⛺",
  // TAMA: "",
  // TAME: "",
  TÄMJ: "🐎",
  // TAMT: "",
  TÄND: "🔥",
  TAND: "🦷",
  TÅNG: "🗜️",
  // TÄNJ: "",
  // TÄNK: "",
  TANK: "🛢️",
  TÄNK: "🧠",
  // TÅNS: "",
  // TANT: "",
  // TÄNT: "",
  TANT: "👵",
  TAPE: "📼",
  // TAPP: "",
  TÄPP: "👃",
  TAPP: "🚰",
  TÄRA: "🦷",
  TARM: "🫃",
  // TÅRS: "",
  // TÄRS: "",
  TÅRS: "😢",
  // TÄRT: "",
  TÅRT: "🍰",
  TÄRT: "😩",
  TASS: "🐾",
  // TÄTA: "",
  // TÄTE: "",
  // TÅTS: "",
  // TÄTS: "",
  // TÄTT: "",
  TAXA: "🧾",
  TAXI: "🚕",
  // TAXS: "",
  // TEAK: "",
  TEAM: "👥",
  // TEDD: "",
  TEER: "⛳",
  // TEES: "",
  TEET: "🍵",
  // TEGS: "",
  TEJP: "🩹",
  // TEKA: "",
  TEMA: "💡",
  TEMP: "🌡️",
  // TENN: "",
  TERM: "📚",
  TEST: "🧪",
  // TETT: "",
  TEVE: "📺",
  TEXT: "📝",
  TIAN: "🔟",
  TIAS: "🔟",
  TICK: "✅",
  TIDS: "⏰",
  TIGA: "🤫",
  TIGG: "🙇",
  // TIGS: "",
  // TIKS: "",
  TILL: "➡️",
  TIMA: "⏱️",
  TINA: "🧊",
  TING: "📦",
  TIOR: "🔟",
  // TIOS: "",
  TIPP: "💡",
  TIPS: "💡",
  TITT: "👀",
  TJAT: "🗣️",
  TJEJ: "👧",
  // TJIM: "",
  TJOA: "📣",
  TJOG: "2️⃣0️⃣",
  // TJOS: "",
  // TJÖT: "",
  TJUR: "🐂",
  TJUT: "📢",
  TJUV: "🥷",
  // TJYV: "",
  TOAN: "🚽",
  // TOAS: "",
  // TOFS: "",
  TOFU: "🫘",
  // TOGS: "",
  TÖJA: "↔️",
  // TÖJD: "",
  // TÖJS: "",
  // TÖJT: "",
  // TOKS: "",
  TOLK: "🗣️",
  TÖLP: "🤡",
  TOLV: "1️⃣2️⃣",
  TÖMD: "🗑️",
  // TÖMS: "",
  // TOMT: "",
  // TÖMT: "",
  TOMT: "🏡",
  TONA: "🎵",
  TONS: "⚖️",
  TÖNT: "🤓",
  TOPP: "🔝",
  TORG: "🏛️",
  TORK: "☀️",
  TÖRN: "🌹",
  TORN: "🗼",
  TORP: "🏡",
  TORR: "🏜️",
  // TÖRS: "",
  TORV: "🌱",
  // TOTA: "",
  // TOTT: "",
  TOUR: "🚌",
  TOVA: "🧶",
  // TRÅD: "",
  TRÄD: "🌳",
  TRÅD: "🧵",
  TRÅG: "🛶",
  TRÄL: "⛓️",
  TRÄN: "🌳",
  // TRÅR: "",
  // TRÅS: "",
  TRÄS: "🌳",
  // TRÄT: "",
  TRAV: "🐎",
  TREA: "3️⃣",
  TREO: "💊",
  // TRES: "",
  TRIO: "👨‍👩‍👦",
  TRIX: "🎩",
  TRÖG: "🐢",
  TRON: "👑",
  // TROR: "",
  // TROS: "",
  TRÖT: "🪫",
  TRUT: "👄",
  // TRYT: "",
  TSAR: "👑",
  TUBS: "🛁",
  TUFF: "💪",
  TUGG: "👄",
  // TUKT: "",
  TULL: "🛃",
  TUMS: "👍",
  TUNG: "🏋️",
  TUNN: "🪶",
  // TUNS: "",
  // TUNT: "",
  TUPP: "🐓",
  TURK: "🇹🇷",
  // TURS: "",
  // TUSS: "",
  TUTA: "📯",
  // TUTT: "",
  // TUVA: "",
  TVÅA: "2️⃣",
  TVÅL: "🧼",
  TVÄR: "↔️",
  TVÅS: "2️⃣",
  TYCK: "💭",
  TYDA: "🔍",
  // TYDD: "",
  // TYDS: "",
  TYGS: "🧵",
  // TYNA: "",
  TYNG: "🏋️",
  // TYPS: "",
  TYSK: "🇩🇪",
  TYST: "🤫",
  // TYTT: "",
  UBÅT: "🚢",
  UDDA: "🔢",
  UDDE: "🏞️",
  // UDDS: "",
  UFON: "🛸",
  UFOS: "🛸",
  UFOT: "🛸",
  UGNS: "🔥",
  // UKIP: "",
  // ULKA: "",
  ULLS: "🐑",
  ULVS: "🐺",
  UNGA: "🧒",
  // UNGE: "",
  // UNGT: "",
  UNIK: "🦄",
  // UNNA: "",
  // UPPÅ: "",
  UPPE: "⬆️",
  URAN: "☢️",
  // UREN: "",
  // URET: "",
  URIN: "🚽",
  URNA: "⚱️",
  USCH: "🤢",
  USEL: "👎",
  // USLA: "",
  // USLE: "",
  UTAN: "🚫",
  UTÅT: "➡️",
  // UTAV: "",
  UTGÅ: "🚪",
  UTGE: "📤",
  UTOM: "➡️",
  UTSÅ: "🌱",
  UTSE: "👉",
  UTTA: "🏧",
  VÄCK: "⏰",
  // VADA: "",
  // VADÅ: "",
  VÅDA: "⚠️",
  VADA: "🚶",
  // VÄDD: "",
  // VADS: "",
  // VAGA: "",
  // VÄGA: "",
  VAGA: "🌫️",
  VÄGA: "⚖️",
  VÅGA: "💪",
  // VÄGD: "",
  // VAGE: "",
  VÄGG: "🧱",
  VAGN: "🚃",
  // VÅGS: "",
  // VÄGS: "",
  VÅGS: "🌊",
  // VAGT: "",
  // VÄGT: "",
  // VAJA: "",
  VÄJA: "↩️",
  VAJA: "🌬️",
  // VÄJS: "",
  // VÄJT: "",
  VAKA: "👁️",
  // VAKS: "",
  VAKT: "💂",
  // VALD: "",
  VÅLD: "👊",
  VALD: "🗳️",
  VÄLJ: "☑️",
  // VALK: "",
  // VALL: "",
  // VÄLL: "",
  VALL: "🌾",
  // VÅLM: "",
  VALP: "🐶",
  VALS: "💃",
  // VALT: "",
  // VÄLT: "",
  // VALV: "",
  // VÄLV: "",
  VALV: "🏛️",
  // VÅMS: "",
  // VANA: "",
  // VÄNA: "",
  VANA: "🔁",
  // VAND: "",
  VÄND: "🔄",
  // VANE: "",
  // VÄNE: "",
  // VÄNJ: "",
  // VANN: "",
  // VÄNS: "",
  // VANT: "",
  // VÄNT: "",
  // VARA: "",
  VÅRA: "🌷",
  VARA: "📦",
  // VÅRD: "",
  // VÄRD: "",
  VÅRD: "🏥",
  VÄRD: "💰",
  // VARE: "",
  VARG: "🐺",
  // VARI: "",
  // VÄRJ: "",
  VÄRK: "🤕",
  VARM: "🥵",
  VÄRM: "🥵",
  VÄRN: "🛡️",
  // VARP: "",
  VÄRP: "🥚",
  VARP: "🧶",
  // VARS: "",
  VÅRS: "🌱",
  // VART: "",
  // VÅRT: "",
  // VÄRT: "",
  // VARU: "",
  // VARV: "",
  VÄRV: "📝",
  VARV: "🔄",
  // VÄSA: "",
  // VASK: "",
  VÄSK: "🎒",
  VASK: "🫧",
  VASS: "🌾",
  VÄST: "🧥",
  // VÅTA: "",
  // VÄTA: "",
  VÅTA: "💧",
  // VÅTE: "",
  VÄTE: "⚛️",
  // VÄTS: "",
  // VÅTT: "",
  // VÄTT: "",
  VÄVA: "🧶",
  // VÄVD: "",
  // VÄVS: "",
  // VÄVT: "",
  // VAXA: "",
  VÄXA: "🌱",
  VAXA: "🕯️",
  // VAXS: "",
  VÄXT: "🪴",
  VECK: "📄",
  VEDS: "🪵",
  // VEKA: "",
  VEKE: "🕯️",
  // VEKS: "",
  // VEKT: "",
  VELA: "🤔",
  // VEMS: "",
  // VENS: "",
  VERB: "🗣️",
  VERK: "🛠️",
  VERS: "📜",
  VETA: "🧠",
  VETE: "🌾",
  VETO: "🚫",
  // VETT: "",
  VEVA: "🔄",
  // VEVS: "",
  VIBB: "📳",
  VICE: "🤵",
  VIDA: "↔️",
  VIDD: "🌊",
  VIFT: "👋",
  VIGA: "💍",
  // VIGD: "",
  VIGG: "⚡",
  // VIGS: "",
  // VIGT: "",
  // VIII: "",
  // VIKA: "",
  // VIKS: "",
  // VIKT: "",
  VILA: "😴",
  VILD: "🐅",
  VILL: "💭",
  // VILO: "",
  VILT: "🦌",
  VINA: "🍷",
  VIND: "💨",
  VING: "🪽",
  VINK: "👋",
  VINN: "🏆",
  VINS: "🍷",
  VIOL: "🎻",
  VIPP: "↕️",
  VIPS: "⚡",
  VIRA: "🌀",
  VISA: "💳",
  VISE: "🧙",
  VISP: "🥄",
  // VISS: "",
  // VIST: "",
  VITA: "⚪",
  VITE: "💸",
  VITS: "😂",
  VITT: "⚪",
  // VOLM: "",
  VOLT: "⚡",
  // VOMS: "",
  VORE: "🤔",
  VÖRT: "🍺",
  // VRAK: "",
  VRÄK: "🏚️",
  VRAK: "🚢",
  VRÅL: "📢",
  VRÅN: "🏠",
  // VRÅR: "",
  // VRÅS: "",
  VRED: "😡",
  VRID: "🔄",
  VURM: "❤️",
  VYER: "🏞️",
  // VYNS: "",
  VYSS: "🤫",
  WATT: "⚡",
  WEBB: "🌐",
  WIKI: "📚",
  WIRE: "🔌",
  WLAN: "📶",
  WOKA: "🥘",
  // WOKS: "",
  XBMC: "📺",
  XIII: "1️⃣3️⃣",
  XVII: "1️⃣7️⃣",
  YARD: "📏",
  YENS: "💴",
  YETI: "👣",
  // YLAR: "",
  // YLAS: "",
  // YLAT: "",
  YLLE: "🧶",
  YMPA: "🌱",
  // YMPS: "",
  YNKA: "🤏",
  YOGA: "🧘",
  // YPPA: "",
  YRAN: "😵",
  // YRAR: "",
  // YRAS: "",
  // YRAT: "",
  // YRDE: "",
  // YRES: "",
  YRKA: "🗣️",
  YRKE: "💼",
  // YRTS: "",
  YSTA: "🧀",
  YTAN: "▫️",
  // YTAS: "",
  YTOR: "▫️",
  // YVAR: "",
  // YVAS: "",
  // YVAT: "",
  // YVES: "",
  // YVIG: "",
  // YVTS: "",
  YXAN: "🪓",
  // YXAS: "",
  YXOR: "🪓",
  ZINK: "🔩",
  ZONS: "🗺️",
  ZOOM: "📹",
  ZOOS: "🦁",
  ÅDRA: "🩸",
  ÅHÖR: "👂",
  ÅKAS: "🚗",
  ÅKEN: "🎢",
  ÅKER: "🚜",
  ÅKTA: "🛷",
  ÅKTE: "🚗",
  ÅLAR: "🐍",
  ÅLEN: "🐍",
  ÅNEJ: "😩",
  ÅNGA: "♨️",
  ÅNYO: "🔁",
  ÅREN: "📅",
  ÅRET: "📅",
  ÅROR: "🚣",
  ÅSAR: "🏔️",
  ÅSKA: "⛈️⚡",
  ÅSNA: "🫏",
  ÅSYN: "👁️",
  ÅTAG: "🤝",
  ÅTAL: "⚖️",
  ÅTER: "🔄",
  ÅTGÅ: "🔥",
  ÅTOG: "🤝",
  ÅTRÅ: "❤️",
  ÅTTA: "8️⃣",
  ÅTTI: "8️⃣0️⃣",
  ÄDEL: "💎",
  ÄDLA: "💎",
  // ÄDLE: "",
  ÄGAN: "👑",
  ÄGAR: "🧑‍💼",
  // ÄGAS: "",
  ÄGDA: "🏠",
  // ÄGDE: "",
  // ÄGER: "",
  // ÄGES: "",
  ÄGGS: "🥚",
  ÄGNA: "🎯",
  ÄGOR: "🏡",
  // ÄGTS: "",
  ÄKTA: "💍",
  // ÄKTE: "",
  ÄLGS: "🦌",
  // ÄLTA: "",
  ÄLVA: "🧚",
  // ÄLVS: "",
  // ÄMNA: "",
  ÄMNE: "📚",
  // ÄNDA: "",
  // ÄNDÅ: "",
  ÄNDA: "🔚",
  ÄNDÅ: "🤷",
  // ÄNDE: "",
  // ÄNGD: "",
  ÄNGS: "🌾",
  ÄNKA: "👩",
  // ÄNKE: "",
  // ÄNNE: "",
  ÄNNU: "⏳",
  ÄRAD: "🏅",
  ÄRAN: "🏆",
  // ÄRAR: "",
  // ÄRAS: "",
  // ÄRAT: "",
  ÄRGA: "🧪",
  // ÄRGS: "",
  ÄRIL: "🔥",
  ÄRMS: "💪",
  // ÄRRS: "",
  ÄRTA: "🫛",
  // ÄRTS: "",
  ÄRVA: "📜",
  // ÄRVD: "",
  // ÄRVS: "",
  // ÄRVT: "",
  ÄSCH: "😒",
  ÄSKA: "📝",
  // ÄTAS: "",
  // ÄTEN: "",
  ÄTER: "🍽️",
  // ÄTES: "",
  // ÄTET: "",
  ÄTIT: "🍽️",
  // ÄTNA: "",
  ÄTTE: "👪",
  // ÄTTS: "",
  ÄVEN: "➕",
  ÖARS: "🏝️",
  ÖBON: "🏝️",
  ÖBOR: "🏝️",
  // ÖBOS: "",
  // ÖDAS: "",
  // ÖDDA: "",
  // ÖDDE: "",
  // ÖDEM: "",
  ÖDEN: "🔮",
  // ÖDER: "",
  // ÖDES: "",
  // ÖDET: "",
  ÖDLA: "🦎",
  ÖDLE: "🦎",
  ÖGAS: "👁️",
  ÖGAT: "👁️",
  ÖGLA: "🪢",
  ÖGNA: "👁️",
  ÖGON: "👀",
  ÖKAD: "📈",
  ÖKAR: "⬆️",
  // ÖKAS: "",
  // ÖKAT: "",
  ÖKEN: "🏜️",
  ÖLEN: "🍺",
  ÖLER: "🍺",
  ÖLET: "🍺",
  ÖMKA: "🥺",
  ÖMMA: "🤕",
  // ÖMME: "",
  ÖMSA: "🐍",
  // ÖMSE: "",
  // ÖRAS: "",
  ÖRAT: "👂",
  ÖREN: "🪙",
  ÖRES: "💰",
  // ÖRET: "",
  // ÖRLA: "",
  ÖRNS: "🦅",
  ÖRON: "👂",
  ÖRTS: "🌿",
  ÖSAS: "🪣",
  ÖSER: "🫗",
  // ÖSES: "",
  ÖSTA: "➡️",
  // ÖSTE: "",
  // ÖSTS: "",
  // ÖTTS: "",
  ÖVAD: "🏋️",
  ÖVAR: "🎯",
  // ÖVAS: "",
  // ÖVAT: "",
  ÖVER: "⬆️",
  ÖVRE: "🔝",
} as const satisfies Partial<Record<Word, string>>;

// Can be sorted using this code (e.g. in Quokka):
// console.log(JSON.stringify(Object.fromEntries(Object.entries(emojis).toSorted((a, b) => a[0].localeCompare(b[0], 'sv')))));
